### PR TITLE
fix command finding in imag/bin/src/main.rs

### LINKED ISSUE #491: imag binary --help doesnt show commands
Hello,
after calling cargo install for every binary and imag/bin, something like
```sh
imag view --help
```
works as expected, however
```sh
imag --help
```
doesnt actually show any comments.
This might as well be a local problem, so this Issue can be closed anytime.
greetings

### PR DESCRIPTION
**Pull request by mario-kr**
this should fix #491

### CODE REVIEW

File: bin/src/main.rs [hunk 1]
```diff
@@ -68,15 +68,19 @@ fn get_commands() -> Vec<String> {
                         .into_iter()
                         .filter(|path| {
                             match path {
-                                &Ok(ref path) => path.path().starts_with(format!("{}/imag-", elem)),
+                                &Ok(ref path) => match path.file_name().to_str() {
+                                    Some(filename) => filename.starts_with("imag-"),
+                                    None => false,
+                                },
```
Comment (matthiasbeyer) [inline bin/src/main.rs]: Would be cleaner here to 

```rust
path.file_name()
    .to_str()
    .map(|f| f.starts_with("imag-"))
    .unwrap_or(false)
```
 IMHO.

File: bin/src/main.rs [hunk 2]
```diff
@@ -68,15 +68,19 @@ fn get_commands() -> Vec<String> {
...
                         })
                         .filter_map(|x| x.ok())
                         .map(|path| {
-                            path.path()
-                                .to_str()
-                                .map(String::from)
+                            match path.file_name().to_str() {
+                                Some(filename) => Some(String::from(filename)),
+                                None => None,
+                            }
```
Comment (matthiasbeyer) [inline bin/src/main.rs]: Why not simply changing the `path()` call to `file_name()`? You don't need to replace everything by a match if you can simply `map` over things here!

**Comment by matthiasbeyer** [comment]
Wow, another PR from you! Awesome!

**Comment by matthiasbeyer** [comment]
Okay, this works... but please fix up the coding style as I mentioned above.

**Comment by matthiasbeyer** [comment]
Thanks a lot!
